# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f6560435661e5a62567c95482cdfb6d15880bb98052bdbbd6e80ac393b0f11cb0f5a4f1b0ab5546f92814cc16d27f8e292e3654f52231293de63d61fcebedfc

test:
  secret_key_base: 2e0481b707fd6d973eada6fc6dd304346223f6a23be5a5b8b77f143e9d21a662df1b0980d85d7a5e430acaf1112fa87c89612e0297aba2934a2016ee686c3c25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
